language: node_js
node_js:
- node
deploy:
- skip_cleanup: true
  provider: script
  script: npm run build && npm run gh-pages
  on:
    branch: master
- skip_cleanup: true
  provider: script
  script: npm run build && npm run gh-pages -- -p "$TRAVIS_BRANCH"
  on:
    all_branches: true
    condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
  email: chris.guindon@eclipse-foundation.org
  name: Christopher Guindon
env:
  global:
    secure: WTpbxbgM3Ehp1bCAblsQBxGoRKyUQN1o503FFAWE3Xlgp8AfAohgNnAB1QtHrB5sP5XlW0r0ijs2nyPcs/zS5qJZTx9+jlhMZFCxSQoBmvOBGrIM+rWtXUUBRm1ccL6fPmbPxDnlkB/igCEzYLo8Heob4kCTAwZAYhF6QKGd/g8Gfk/B93bipJSLk2pbAX629ZfRluJqUwlUY7TY3W10hLPpehh6Q/+SNFP1SQZgNf9R0OwtKdQFsKPZc3ZyhYhXCUEEcck0tBqcMIEf6tHOtfy+5e9Zeu59jHEX/zTwj54UmQ/er4RyOUDfZC+/upDnqa0aDjwbyfzW+3QF9ciQ8SgS4vFdE17ucv8G2GeibH5SdlCppoWt35AVP0Rn++EIbAvDT4/hlw+2OwcmkXcFQ55Mlm5Mx0r3ISuo5TEFCiCZ918apLRIomTFDGwmFSJO7KAflQ0VbmJIIIY4telnrUyb5GgOcRQ9ovVt1DPVsukgYpjM5HCkyyDi7FUKPCF/+KW+rAuc0Gd6YYmNP0bicwzMOjewVNIsoQyhBGkmPXXsA3P0ANlhozNF1Fh0g5V8J64Xyhk09u9XxiabUpJOl6QkzufsbMr5aLqs1/G9bwv3fF8m5xk3GS9xUc2mFpprXFIiYv0yPhloawI/qdvYvXd9faXO8Sn66HMrB6XQIZc=
