# Group External REST api

### Bugzilla REST API
+ **Url:** https://bugs.eclipse.org/bugstest
+ **Documentation:** https://wiki.mozilla.org/Bugzilla:REST_API
+ **Example:** https://bugs.eclipse.org/bugstest/rest/product/BIRT
+ **This API will be available with production data after the upgrade on Nov 26 via https://bugs.eclipse.org/bugs.**

### Gerrit Rest API
+ **Url:** https://git.eclipse.org/r/
+ **Documentation:** https://gerrit-review.googlesource.com/Documentation/rest-api.html
+ **Example:** https://git.eclipse.org/r/projects/

### Jenkins REST API
+ **Url:** https://ci.eclipse.org/
+ **Documentation:** https://wiki.jenkins.io/display/JENKINS/Remote+access+API
+ **Example:** https://ci.eclipse.org/californium/job/1.0.x/lastBuild/api/json

### Api.eclipse.org API
+ **Url:** https://api.eclipse.org
+ **Documentation:** https://api.eclipse.org/
+ **Example:** https://api.eclipse.org/account/profile/cguindon/forum
+ **Source code:** https://github.com/chrisguindon/api.eclipse.org-docs 

### Eclipse Marketplace API
+ **Url:** http://marketplace.eclipse.org/
+ **Documentation:** https://wiki.eclipse.org/Marketplace/REST
+ **Example:** https://marketplace.eclipse.org/category/markets/tools/api/p