# Group Mailing Lists

Eclipse Mailing Lists are available through this resource.

## Fetch Mailing lists Metadata [GET /mailing_lists/metadata{?name,search,page,pagesize,order_by}]

### Overview

Retrieve metadata for all the mailing lists.

### Result definition

+ **list_name:** name of the mailing list
+ **url:** url of the mailing list
+ **email:** email of the mailing list

+ Parameters
    + name (string, optional) - The name of a specific mailing list
    + search (string, optional) - A keyword to search for in a mailing list name
    + page (integer, optional) - The index of the page to get, defaults to 1.
    + pagesize (integer, optional) - The number of records to get per page, defaults to 20. Maximum value is 100.
    + order_by (string, optional) - The order by name in which the results will be returned. ASC by default

+ Response 200 (application/json)
    + Headers
        Link:<https://api.eclipse.org/mailing_lists/metadata?page=1&amp;pagesize=20>; rel="next", <https://api.eclipse.org/mailing_lists/metadata?page=99&amp;pagesize=5>; rel="last", <https://api.eclipse.org/mailing_lists/metadata?page=1&amp;pagesize=5>; rel="first", <https://api.eclipse.org/mailing_lists/metadata?page=1&amp;pagesize=5>; rel="self"
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Content-Type: application/json
        
    + Body
        [{"list_name":"example-list1","url":"https://accounts.eclipse.org/mailing-list/example-list1","email":"example-list1@eclipse.org"},{"list_name":"example-list2","url":"https://accounts.eclipse.org/mailing-list/example-list2","email":"example-list2@eclipse.org"}]


