# Group Eclipse USS
The Eclipse User Storage Service (USS) allows Eclipse projects to store user-specific project information on the 
Eclipse Foundation servers. The goal is to make it easy for our projects to offer a 
better user experience by storing relevant information in a central location.

The BLOB resource is a way for projects to store binary objects based off a application_token/key value pair.
 
The “value” is always the last element in this JSON structure. All other things must come before that so that 
the SDK implementation can parse and collect them into a Map and finally return a decoding InputStream to 
deliver the “value” content back to the caller/application. The blob value is available when the 
client retrieve a specific blob using an application_token and key.
 
We are using application_token and key to identify a blob. The Application token is a string that is assigned by the 
Eclipse Management Organization.The key string must respect the following validation rules: 

* 5-25 characters;
* letters: lowercase and uppercase/numbers/underscores are valid;
* each string should start with a letter.

## Fetch Blobs [GET /uss/blob{?page,pagesize}]
Retrieve a list of all the blobs for a user. Requires the `uss_retrieve` scope.

+ Parameters
    + page (integer, optional) - The index of the page to get, defaults to 1.
    + pagesize (integer, optional) - The number of records to get per page, defaults to 20. Maximum value is 100.

+ Request
    + Headers
        Authorization: Bearer ec342fe0d66baab3c4b42549f
        Accept: application/json
        User-Agent: USER_AGENT
        Accept: application/json
        Content-Type: application/json

+ Response 401 (application/json)
    + Headers
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Content-Type: application/json
        
+ Response 200 (application/json)
    + Headers
        Link: <https://api.eclipse.org/uss/blob?page=1&amp;pagesize=20>; rel="last", <https://api.eclipse.org/uss/blob?page=1&amp;pagesize=20>; rel="first", <https://api.eclipse.org/uss/blob?page=1&amp;pagesize=20>; rel="self"
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Content-Type: application/json
        
    + Body
        [{"application_token":"MZ04RMOpksKN5GpxKXafq2MSjSP","etag":"9f76b4dde4cb5146daa5686a7f4376084dbe41bf9c9d4a12b722fe1062eb48eb","changed":"1497030093","key":"mpc_favorites","url":"https://api.eclipse.org/account/profile/1/blob/MZ04RMOpksKN5GpxKXafq2MSjSP/mpc_favorites"}]
        
## Search Blobs [GET /uss/blob/{application_token}/{blob_key}{?page,pagesize}]
Search specific user blob object. Requires the `uss_retrieve` scope.

+ Parameters
    + `application_token` (string, required) - Unique identifer of the project, e.g, eclipse.org.oomph.
    + `blob_key` (string, optional) - Unique identifier of the profile setting to save, e.g, install_xml.
    + `page` (integer, optional) - The index of the page to get, defaults to 1.
    + `pagesize` (integer, optional) - The number of records to get per page, defaults to 20. Maximum value is 100.

+ Request
    + Headers
        Authorization: Bearer ec342fe0d66baab3c4b42549f
        Accept: application/json
        User-Agent: USER_AGENT
        If-None-Match: 54d66cdf0a31cf65bf3f6c9888fc3efdd51dd079f5da4200d7e6ccb399b25a61
        Accept: application/json
        Content-Type: application/json
        If-Modified-Since: Wed, 21 Oct 2015 07:28:00 GMT

+ Response 401 (application/json)
    + Headers
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Content-Type: application/json
        
        
+ Response 304 (application/json)
    + Headers
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Etag: "9f76b4dde4cb5146daa5686a7f4376084dbe41bf9c9d4a12b722fe1062eb48eb"
        Content-Type: application/json
        
+ Response 200 (application/json)
    + Headers
        Link: <https://api.eclipse.org/uss/blob?page=1&amp;pagesize=20>; rel="last", <https://api.eclipse.org/uss/blob?page=1&amp;pagesize=20>; rel="first", <https://api.eclipse.org/uss/blob?page=1&amp;pagesize=20>; rel="self"
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Etag: "9f76b4dde4cb5146daa5686a7f4376084dbe41bf9c9d4a12b722fe1062eb48eb"
        Content-Type: application/json
        
    + Body
      {"application_token":"MZ04RMOpksKN5GpxKXafq2MSjSP","etag":"9f76b4dde4cb5146daa5686a7f4376084dbe41bf9c9d4a12b722fe1062eb48eb","changed":"1497030093","key":"mpc_favorites","url":"https://ape.gclipse.local:51243/account/profile/1/blob/MZ04RMOpksKN5GpxKXafq2MSjSP/mpc_favorites","value":"MzI3NDQwNQ=="}

## Delete Blobs [DELETE /uss/blob/{application_token}/{blob_key}]
Delete a blob for a user. Requires the `uss_update` scope.

+ Parameters
    + `application_token` (string, required) - Unique identifer of the project, e.g, eclipse.org.oomph.
    + `blob_key` (string, optional, required) - Unique identifier of the profile setting to save, e.g, install_xml.
    
+ Request
    + Headers
        Authorization: Bearer ec342fe0d66baab3c4b42549f
        Accept: application/json
        User-Agent: USER_AGENT
        If-None-Match: 54d66cdf0a31cf65bf3f6c9888fc3efdd51dd079f5da4200d7e6ccb399b25a61
        Accept: application/json
        Content-Type: application/json
        
+ Response 401 (application/json)
    + Headers
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Content-Type: application/js
        
+ Response 204 (application/json)
    + Headers
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Content-Type: application/js
        
## Update/Create Blobs [PUT /uss/blob/{application_token}/{blob_key}]
Delete a blob for a user. Requires the `uss_update` scope.

+ Parameters
    + `application_token` (string, required) - Unique identifer of the project, e.g, eclipse.org.oomph.
    + `blob_key` (string, optional, required) - Unique identifier of the profile setting to save, e.g, install_xml.
    
+ Request
    + Headers
        Authorization: Bearer ec342fe0d66baab3c4b42549f
        Accept: application/json
        User-Agent: USER_AGENT
        If-Match: 54d66cdf0a31cf65bf3f6c9888fc3efdd51dd079f5da4200d7e6ccb399b25a61
        Accept: application/json
        Content-Type: application/json
        
+ Response 401 (application/json)
    + Headers
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Content-Type: application/js
        
+ Response 201 (application/json)
    + Headers
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Content-Type: application/js
        Etag: "9f76b4dde4cb5146daa5686a7f4376084dbe41bf9c9d4a12b722fe1062eb48eb"
        
    + Body
       {"url":"https://api.eclipse.org/api/blob/:namespace/:key"}
        
+ Response 200 (application/json)
    + Headers
        X-Rate-Limit-Limit: 1000
        X-Rate-Limit-Remaining: 964
        X-Rate-Limit-Reset: 3553
        Content-Type: application/js
        Etag: "9f76b4dde4cb5146daa5686a7f4376084dbe41bf9c9d4a12b722fe1062eb48eb"