FORMAT: 1A
HOST: https://api.eclipse.org/

# Eclipse Api RESTful API
Eclipse Fountation resources and data.

### Authentication
*Eclipse Api RESTful API* uses OAuth Authorization for protected resources.

### Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) 
are used.

<!-- include(modules/marketplace_favorites.apib) -->
